CREATE DATABASE THEHOST
GO

USE THEHOST
GO

CREATE TABLE CLIENTE (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (11) NOT NULL,
TELEFONE VARCHAR(11) NOT NULL
)

CREATE TABLE FUNCIONARIO (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (11) NOT NULL
)

CREATE TABLE QUARTO (
ID INT PRIMARY KEY NOT NULL,
NUMERO INT NOT NULL,
ANDAR INT NOT NULL,
TIPO VARCHAR (10) NOT NULL
)

CREATE TABLE HOSPEDAGEM (
ID INT PRIMARY KEY NOT NULL,
ENTRADA DATE not null,
SAIDA DATE,
VALOR NUMERIC(7,2),
CLIENTE_ID INT FOREIGN KEY REFERENCES CLIENTE(ID),
QUARTO_ID INT FOREIGN KEY REFERENCES QUARTO(ID)
)